// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgshpvvlmttytihdgeoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnc2hwdnZsbXR0eXRpaGRnZW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODExMDcsImV4cCI6MjA3MjQ1NzEwN30.O1xE0HV5bbq1J2G1dcXqUPdUC7HfoUOs83fSXTKd5dQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});